//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempus4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int AvailabilityID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int JobID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> AdministratorsId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
        public virtual Administrator Administrator { get; set; }
    }
}
